name: CIT Kafka

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  kafka:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
        go-version: 1.19.x

    - name: Run kafka integration tests
      run: bash scripts/kafka-integration-test.sh
    
    services:
      zookeeper:
        image: bitnami/zookeeper
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: yes
      kafka:
        image: bitnami/kafka
        ports:
          - 9092:9092
        env:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
