name: Deploy

on:
    workflow_dispatch:
        inputs:
            dockerImageTag:
                description: 'Docker image tag to deploy'
                required: true

jobs:
    deploy:
        name: Deploy docker image to ECS
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '15'

            - name: Install dependencies
              working-directory: scripts
              run: npm install

            - name: Deploy
              working-directory: scripts
              run: npx ts-node deploy.ts
              env:
                  DOCKER_IMAGE_TAG: ${{ github.event.inputs.dockerImageTag }}
                  DEPLOY_AWS_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
                  DEPLOY_AWS_SECRET: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
                  AIRBRAKE_PROJECT_ID: 380559
                  AIRBRAKE_PROJECT_KEY: ${{ secrets.AIRBRAKE_PROJECT_KEY }}
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

            - name: Notify Slack
              if: ${{ success() }}
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  SLACK_USERNAME: helios-ci-bot
                  SLACK_TITLE: jaeger-query
                  SLACK_MESSAGE: Image tag ${{ github.event.inputs.dockerImageTag }} was successfully deployed!
                  SLACK_COLOR: ${{ job.status }}
